### ISSUE TITLE
Bar not showing, no entry in settings

### ISSUE THREAD

**Issue by Launert** [ironmonk88/always-hp#1]
Hello,

I seems to be unable to get the HP bar to show and no settings are available under Configure Settings -> Module settings.

Foundry 0.7.9
No other modules active.
![grafik](https://user-images.githubusercontent.com/47757241/104205941-43a4c500-542f-11eb-8118-b5e6e3a4e7c4.png)
![grafik](https://user-images.githubusercontent.com/47757241/104206070-6931ce80-542f-11eb-959b-ebe4a91f648c.png)

**Comment by ironmonk88** [comment]
There currently aren't any module settings to configure, so nothing will appear there.
Usually, when first run, Always HP shows up in the upper leftish corner.
If it's not there, then either there's an error rendering it, or possibly it's off the screen somewhere.
How comfortable are you with the developer tools of your browser?

**Comment by crlong02** [comment]
I have the same issue.  It's not on the screen anywhere and there are no errors with rendering per the console.

**Comment by ironmonk88** [comment]
Found the issue.
The bar was only showing if it had been shown before, and been moved.
Could you try updating your version and checking to see if it works now.

**Comment by ironmonk88** [comment]
Yayyy!!  Thank you for catching that one.

**Comment by Launert** [comment]
Works now! Thanks!
