### ISSUE TITLE
Death Save Tick Marks don't update immediately

### ISSUE THREAD

**Issue by GambetTV** [ironmonk88/always-hp#12]
When a token does a death save, the tick mark doesn't update until you click off the token and back on it! Thanks!

**Comment by ironmonk88** [comment]
What system are you using, and can you list the steps to take to reproduce it?

**Comment by GambetTV** [comment]
D&D5e and... I don't know, doing a Death Save from within the character sheet. That's it? It's not too complicated, it just doesn't show the tick marks unless I click off the token and back on it.

**Comment by ironmonk88** [comment]
I think this should have already been fixed.
If it hasn't been, please re-open the ticket.
