### ISSUE TITLE
Enhancement suggestion. Temporary hitpoints

### ISSUE THREAD

**Issue by Bryn1701** [ironmonk88/always-hp#18]
I love using this module. It speeds things up for me as both GM and my players. I was curious if you could add the calculation for temporary hit points. It currently takes away temp hit points first when entering damage, but the output doesn't show how many temp hit points they currently have. 

Thanks!

**Comment by ironmonk88** [comment]
This was added awhile back.  Just cleaning up the tickets.

**Comment by Wizard-Level-1** [comment]
Was this feature removed?  Recently started using this mod, but I don't see a temp HP button or option?

**Comment by ironmonk88** [comment]
https://github.com/ironmonk88/monks-module-wiki/wiki/Always-HP
Type in something like `+t5`
