### ISSUE TITLE
Clicking the Heart symbol doesn't remove skull status icon, sometimes.

### ISSUE THREAD

**Issue by jocolamarco** [ironmonk88/always-hp#20]
Sometimes, when clicking the heart on dead npcs, it doesn't remove the skull symbol.. Is this expected behaviour for this module or is it dependent on something else?

**Comment by ironmonk88** [comment]
What system are you using? DnD5e?

It's not expected behavior, but some systems handle that skull symbol differently.

**Comment by jocolamarco** [comment]
DnD5e yes. I just figured it out, it was a different module doing that.
