### ISSUE TITLE
Multi-select, Clicking Heart symbol doesn't apply HP recovery properly

### ISSUE THREAD

**Issue by jocolamarco** [ironmonk88/always-hp#23]
fvtt 0.8.8
dnd5e 1.4.2
always-hp 1.0.26

Steps:
1 - Select multiple tokens that are damaged
2 - Click the Heart symbol in AlwaysHP
3 - Both the console log and the "Combat numbers" module display the expected change but HP doesn't update in the token:

Video:
![alwayshp](https://user-images.githubusercontent.com/45291719/129872917-80c94809-55e1-4af0-ab0f-acf6e5480c0f.gif)

Log:
![image](https://user-images.githubusercontent.com/45291719/129869214-919f691d-2240-4459-8d36-cd769adc5607.png)

I can share the actor data from the log if needed - it's just too big, not sure if there's a specific field to check?

**Comment by pesky-wobbit** [comment]
It heals the first token correctly then heals everyone else the same number of HP (instead of fully healing them).

**Comment by davelacorneille** [comment]
Same for me.

**Comment by ironmonk88** [comment]
Should be fixed in the latest version.
