### ISSUE TITLE
Alignment issue

### ISSUE THREAD

**Issue by Argonaut13** [ironmonk88/always-hp#24]
If I align the window to the left side of my canvas like in the image, I cannot use the kill or damage buttons. If I inch the window over to the right, it eventually allows me to: it is as if there is some invisible dead zone. This only occurs with Always HP. I put Monk's Token bar in the same position, and its buttons are even closer to the edge of the window, yet I can click them with no problem.

It works as intended elsewhere on the canvas/screen.
![Weird Issue](https://user-images.githubusercontent.com/24908933/132472938-7d841fd8-f373-4243-b219-73bdc9e4eaea.jpg)

**Comment by Argonaut13** [comment]
Not to nag, but is there any solution to this?

**Comment by ironmonk88** [comment]
Closing this as there hasn't been a response.  Assuming the new changes fixed the issue.
