### ISSUE TITLE
Visibility/overlapping  problem

### ISSUE THREAD

**Issue by cal413** [ironmonk88/always-hp#26]
![image](https://user-images.githubusercontent.com/76707578/134071716-7bb4f713-5032-41d4-a9d8-0d245b0088ad.png)

Hi, I'm in Dungeon World system, the HP window overlaps with the otrher menus.
I verified the error in a new fresh world without any other module, same problem.
![image](https://user-images.githubusercontent.com/76707578/134071840-0b8198a2-1e16-44aa-98f4-7e40a1dfb743.png)

**Comment by ironmonk88** [comment]
Closing as there is a solution to the issue.
