### ISSUE TITLE
FEATURE REQUEST: Option to hide the "Toggle AlwaysHP Dialog" button

### ISSUE THREAD

**Issue by GambetTV** [ironmonk88/always-hp#28]
I use a lot of modules, and there's a lot of buttons clogging my left hand screen. I always leave your screen up, and would never disable it, but the button to toggle it on and off has no option to put it away. I can see the use for some people, but would it be too much trouble to also add a menu option to remove that button for those of us who don't need it?

**Comment by ironmonk88** [comment]
Added this option to the latest release.
