### ISSUE TITLE
What systems does this support?

### ISSUE THREAD

**Issue by akrigline** [ironmonk88/always-hp#3]
Recommend tagging this with what systems it supports, there's no indication if this works for dnd5e, pf1, pf2, etc etc. The Admin panel has a mutli select which shows installing users what systems are supported, or simply including a line in the description/readme would be helpful.

**Comment by ironmonk88** [comment]
Added the information to the website.  Currently set to just DnD5e and PFv2, but I suspect there are more it can be used with.  I'll need to test them first.
