### ISSUE TITLE
Create option to hide from players

### ISSUE THREAD

**Issue by GambetTV** [ironmonk88/always-hp#30]
With the recent updates you made the HP bar visible for all players. If this is intentional can you please create an option for the GM to turn it off for the players?

**Comment by amcvfx** [comment]
I would also like to turn it off for players! I think this is how it used to work?

**Comment by ianm32** [comment]
This is important to me, as well!

**Comment by funwithfondue** [comment]
+1 for this from me

**Comment by ironmonk88** [comment]
Added the feature to display to everyone, GM, or players only.

**Comment by funwithfondue** [comment]
@ironmonk88 thanks! The latest version doesn't seem to be coming through to me on Foundry. It still shows 1.0.27 and says it's the latest version.
