### ISSUE TITLE
Escape (Esc) Key Not Working

### ISSUE THREAD

**Issue by PhluXx1** [ironmonk88/always-hp#32]
The Always HP module is interfering with the Esc key in Foundry version 9 latest Build 238. 

When the Esc key is pressed nothing happens whilst the module is enabled. With toggling you can get Escape to function normally by toggling the dialogue to off. 

This has been tested on a fresh world with only Always HP enabled and the issue still persists.

**Comment by PhluXx1** [comment]
Been waiting 2 weeks on this do you have any update on this?

**Comment by ironmonk88** [comment]
Always HP is currently in queue behind Enhanced Journals, Tokenbar, Active Tiles, Little Details, and Common Display.
There's a lot of work to do.

**Comment by PhluXx1** [comment]
@ironmonk88 Thanks for the updated just wanted an idea on the situation. I've reverted to 0.8.9 and will hold off on v9 for a while.

**Comment by ironmonk88** [comment]
Latest release should have this fix.
