### ISSUE TITLE
make "float away" health numbers a thing with Always HP

### ISSUE THREAD

**Issue by miromonti** [ironmonk88/always-hp#34]
I don't know the name of this feature, but this float-away health number thing that's built into Foundry 9...

https://user-images.githubusercontent.com/38819125/152674126-0603052c-3e30-4af9-b9aa-d89ab62b2773.mov

...doesn't play when Always HP applies health changes. It'd be great if it did.

I know the module Combat Numbers does the same thing, but I'd like to keep my module count down, especially when the feature is built into the game.

Foundry VTT 9.249
DnD5e 1.5.7
Tested with Always HP 1.0.32 and Find the Culprit 1.4.0

**Comment by Bryn1701** [comment]
I would also like to see this work with Foundries build in Scrolling Status Text for damage and healing!

**Comment by ironmonk88** [comment]
Should be available in the current release.
