### ISSUE TITLE
Allow the AlwaysHP Popup to open where it was last closed

### ISSUE THREAD

**Issue by KellethDregar** [ironmonk88/always-hp#35]
Unless I'm mistaken this was the normal behavior in older versions of AlwaysHP when it was closed or you left Foundry and came back it would remember where it was last closed at. At some point in the versions it seems to now reset to the same spot on the top right of the screen for both toggling it on and off with the button or each time you load into foundry. 

Not sure if this would be an enhancement request or if it's a bug or intentional change but couldn't find it in the change logs.

**Comment by ironmonk88** [comment]
Are there any errors in the console log or have you used Find the Culprit to see if there's any other module interference? 
It should open where you last left it.

**Comment by ironmonk88** [comment]
Closing this as there's been no response and I can't replicate it.
