### ISSUE TITLE
[Feature Request] Drag numeric HP total to adjust

### ISSUE THREAD

**Issue by LukasPrism** [ironmonk88/always-hp#37]
I LOVE this module!

But I have to admit, as soon as I saw the green box with HP in it, I tried dragging it to see if the HP adjusted. A bit like the sun/moon in SmallTime. 

I think if you could nail this, it would hands-down be the fastest way to make HP adjustments. Sure, on tokens with high HP value, the increments would be smaller and hitting the exact number might be tricky – but you’ve already got that covered with the buttons that increment by 1. So, get close enough then use the buttons to mop up (if you need to).

Of course you’d need a number to pop up next to the total to show how many you’re adding or removing eg -15 or +12 (so poor GMs don’t need to do any mental math).

Thanks again for your wonderful modules. Really enjoyed your interview with Baileywiki :)

**Comment by LukasPrism** [comment]
Actually the modifier should just display in the main input as you're dragging, duh!

**Comment by ironmonk88** [comment]
Should be available in the current release.
