### ISSUE TITLE
Add the option that HP can directly be modified in the text field

### ISSUE THREAD

**Issue by Falerion-git** [ironmonk88/always-hp#4]
Add in the options menu the possibility to turn on direct input in the HP field.  

Entering a positive or negative number in the HP field and pressing enter could then directly be accepted as input, as it is currently done with the arrow up/down buttons.

User experience:
The user is already using the keyboard to enter the numbers into the HP field. Just hitting the Enter key may speed up the input.

**Comment by ironmonk88** [comment]
Added in 1.0.9
Set it so a + in front of the number will heal, anything else will hurt.
