### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by heyzoms** [ironmonk88/always-hp#40]
After latest update. It seems not to work anymore. mostly not applying the hp loss when i have a token selected. This is what the it looks like when i have a token selected. idk if that helps 
![Screenshot (148)](https://user-images.githubusercontent.com/109550182/179584384-16abfc97-e612-4591-bce9-89140b224e57.png)

**Comment by GambetTV** [comment]
Same. Since the most recent update this module is no longer functional.

**Comment by ironmonk88** [comment]
There was an issue with the manifest and Foundry was allowing the v10 update to be installed on a v9 system.
Fix should be up on the server, you'll have to uninstall an re-install.

**Comment by heyzoms** [comment]
Do i need to update to v10? because after reinstalling on v9 it still doesn't work

**Comment by heyzoms** [comment]
ok its fix now, thank!
