### ISSUE TITLE
Doesn't update the Token HUD

### ISSUE THREAD

**Issue by geoidesic** [ironmonk88/always-hp#41]
Changing HP in always-hp doesn't update the Token HUD immediately,, have to close and re-open the HUD to get it to display

**Comment by ironmonk88** [comment]
To be fair... I think this is a Foundry issue, not an Always HP issue.  If you have the Token HUD open and then open the Actor sheet and change the HP on the Actor sheet, the HUD isn't updated.

I've submitted a bug report with Foundry.

**Comment by ironmonk88** [comment]
Closing this as Foundry has reported it as having been fixed.
