### ISSUE TITLE
Feature Request: API to allow macro manipulation of the Always HP window

### ISSUE THREAD

**Issue by shirkie** [ironmonk88/always-hp#42]
It would be helpful to be able to have an API to allow manipulation of the always HP window by macros.  In particular, for being able to toggle the window on and off.

Extra nice feature would be to be able to optionally set the Always HP window's text box as focused when turning the window on for ease of use.

**Comment by ironmonk88** [comment]
Added tot he latest version.
Use `game.AlwaysHP.app` to get access to the Apllication.  And `game.AlwaysHP.toggleApp(show)` to toggle the window.  show is true or false, or leave it blank to toggle.
