### ISSUE TITLE
[BUG] [Pf2e] Killing or reviving token through Always HP doesn't apply or remove defeated status

### ISSUE THREAD

**Issue by weepingminotaur** [ironmonk88/always-hp#48]
If you use the skull button or just straight damage to kill a PC or NPC using Always HP, the monster does not gain the defeated status as it should if the setting in either Always HP or Monk's Little Details is on. Similar issue with healing -- when you heal a token via Always HP, it does not remove the defeated status.

Foundry v10 288, PF2e v.4.2.6.

**Comment by ironmonk88** [comment]
Should be fixed in the latest version
