### ISSUE TITLE
[BUG] Using "Bar Click" option when a value is already entered in the text box results in two values overlapping each other

### ISSUE THREAD

**Issue by GambetTV** [ironmonk88/always-hp#49]
When using the "Bar Click" option that lets us hover over the HP bar to alter the attribute, it populates a number inside of the text window showing how much damage is being added/subtracted. However, if a number has already been entered in the text window, using Bar Click results in both numbers overlapping each other in a jumbled, incoherent mess. 

![image](https://user-images.githubusercontent.com/72000497/205340999-8bf95a07-1b38-4a1b-baa0-9849064a24c7.png)

**Comment by ironmonk88** [comment]
Should be fixed in the latest version
