### ISSUE TITLE
Option to disable showing death save results

### ISSUE THREAD

**Issue by 3DSTyler** [ironmonk88/always-hp#50]
**Is your feature request related to a problem? Please describe.**
I use a module to do blind GM death saves, so only I know the results to make things more intense and dramatic. AlwaysHP is handy for my players but displays the pips for death saves, defeating the purpose.

**Describe the solution you'd like**
A checkbox setting to hide the death save pips from non-gm accounts.

**Additional context**
Screenshot shows character sheet (tidy5e) where it doesn't show success/fails, chat with no roll results because its hidden, but AlwaysHP shows pips. 
[https://i.imgur.com/mnTYX3o.jpeg](url)

**Comment by ironmonk88** [comment]
Added to the most recent release.
