### ISSUE TITLE
Support for Shadow of the Demon Lord?

### ISSUE THREAD

**Issue by zaksquatch** [ironmonk88/always-hp#51]
Essentially, is there a way we can set this to work inversely?

Shadow of the Demon Lord as a system tracks _damage_ instead of _health_. So a character at 0 is considered perfectly healthy, where one at the maximum is dead so-to-speak.

**Comment by ironmonk88** [comment]
![image](https://github.com/ironmonk88/always-hp/assets/75920956/d2aaa667-3282-4073-b7e1-2fb4b88f7d2e)
