### ISSUE TITLE
[BUG] Selecting Group Token produces console error message

### ISSUE THREAD

**Issue by SirMotte** [ironmonk88/always-hp#52]
**Describe the bug**
An error messageis shown in the console log that is related to this module.

**To Reproduce**
1. Create a Group Token, introduced with DnD 2.1.0, and fill it with some actors.
2. Click on the Token while always HP is active.
3. Check console log

**Expected behavior**
Add some kind of support or ignore flag to Group Tokens.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/82598692/215131780-2d6c6ac5-0630-4175-843a-b084a2238937.png)

**Please complete as much of the following information as possible:**
 - Foundry Client
 - Foundry Version 10.291
 - System DnD 5e v2.1.4
 - Module version 10.5

**Comment by ironmonk88** [comment]
Closing this at it should be fixed in the latest release.
