### ISSUE TITLE
[BUG] Module updates to same version 11.01 > 11.01

### ISSUE THREAD

**Issue by r-valyar** [ironmonk88/always-hp#56]
**Describe the bug**
Module updates itself to same version

**To Reproduce**
Initiate module update from the Add-On interface of Foundry v10 (latest) or v11 (latest)

**Expected behavior**
Module updates itself to the same version. 

**Screenshots**
![image](https://github.com/ironmonk88/always-hp/assets/63558984/974a3599-0f2b-4498-b7b2-ed638549cdcd)

![image](https://github.com/ironmonk88/always-hp/assets/63558984/c700190d-765f-4ccd-8cc0-b4f5e84605d4)

**Please complete as much of the following information as possible:**
 - Foundry Version v10.291 & v11.300
 - System n/a
 - Module version 11.01
 - Are there any errors in the console [e.g. press F12 and look for red text]
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction.

**Additional context**

**Comment by PwQt** [comment]
No longer occurs on 11.03

**Comment by ironmonk88** [comment]
Closing issue as it should be fixed.
