### ISSUE TITLE
Turn off for players

### ISSUE THREAD

**Issue by amcvfx** [ironmonk88/always-hp#6]
Could we get an option to turn the floating window off for players? They don't need to use it and it takes up space on small screens,

**Comment by ironmonk88** [comment]
Version 1.0.16 has been released.  Players can now toggle the Dialog individually via Configure Settings.

**Comment by JJBocanegra** [comment]
I think it's better an option for the GM to directly disable it for players, my players are not tech savvy and they always have problems finding options to change.

**Comment by amcvfx** [comment]
I agree! Having the DM use a global switch to turn it off would be better

**Comment by gfactor** [comment]
I think having both options would be better: a global toggle for the GM to disable the Always HP bar for all players, and player toggles for individual players to turn off the bar.

**Comment by JJBocanegra** [comment]
You let your players touch the HP? 😮

**Comment by gfactor** [comment]
XD Yeah, for their own characters. I was OK with letting them track their character's HP when we played at a physical table. I'm OK with letting them track it at a virtual table too. And if I really need to check, I have access to the HP bar and their actor sheet to double-check they're applying damage/healing correctly.

They don't have permissions to select other tokens, so they can't change the HP of other players' characters or enemies.
