### ISSUE TITLE
Several bugs with setting multiple characters to dead/fully healing simultaneously.

### ISSUE THREAD

**Issue by GambetTV** [ironmonk88/always-hp#9]
If you select multiple characters and Set them to dead, they will sometimes have their HP reduced only by a number equal to the lowest HP member of that group. Example: Character A has 10 HP, Character B has 12, I select both, click Set to Dead, Character A drops to 0 HP, character B drops to 2 HP, but both still have the dead status applied to them.

When multiple characters are set to dead, this seems to trigger some kind of bug, that when you give them HP, set them to fully healed, do individually or as a group, it doesn't matter, it will not automatically remove the Skull status icon from their token. However, when you refresh the window, the status icon won't be there anymore, but this requires every player/DM to refresh to fix the issue.

**Comment by GambetTV** [comment]
Just to provide some extra context to this, I suspect using the "Fully Heal" button might restore HP, but doesn't trigger all the conditions of being fully healed. I'm also using the Blood & Guts module, which upon receiving any healing it's supposed to stop your character from bleeding, but using the fully heal button (again, on multiple tokens at once) doesn't stop all of them from continuing to bleed, at which point the only way to fix it is to manually lower and then raise their HP.

**Comment by ironmonk88** [comment]
Thank you for catching that.  I needed to wait for some functions to finish before continuing with the code.  Foundry has a bad habit of dropping database changes if too many are posted at it at once.  I think this should have it fixed, but I havn't been able to test with Blood and Guts yet.
